### PR TITLE
Scaffolding TS plugin compilation

### PR DESCRIPTION
**Pull request by robobenklein**
I have no idea if this works or not.

Still a lot of work to do for the Atom plugin interface.

### CODE REVIEW

**Comment by ilumsden** [comment]
We should take a look at this if we need to directly use Atom's API: http://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html

**Comment by robobenklein** [comment]
I looked at the consumption of atom events, but I don't know what we'd be consuming yet, so I didn't add that section in.

As for TS spec consumption, well we don't have any code to consume yet...

**Comment by ilumsden** [comment]
Actually, it looks like you already have packaging stuff for that set up. I'm pretty sure all that has to be done for that is including `@types/atom` as a dependency.

**Comment by ilumsden** [comment]
The way I see it, the only change with TypeScript is with the `lib` and `dist` directories. With JavaScript, you'd usually have your source code in `lib`, and `package.json` would use `lib` for the immediate functionality. With TypeScript, you need the intermediate transpilation to JavaScript (which outputs to `dist`), and then `package.json` uses the transpiled JavaScript for immediate functionality.

**Comment by ilumsden** [comment]
Actually, @robobenklein, you might need to merge `master` into this branch before merging the PR. Your current branch still has the `submodules.md` file in it, which is not in `master` anymore.

**Comment by robobenklein** [comment]
`submodules.md` wasn't in any of the commit refs so it's not included, but you're right that for code that should have been a backmerge before merge.

**Pull request merged**
